### ISSUE TITLE
Bug when using big indexes

### ISSUE THREAD

**Issue by lmammino** [lmammino/indexed-string-variation#8]
Sample code:

``` javascript
var isv = require('indexed-string-variation').default;

var i = 3511326342653452173122134435345;
console.log(i);
console.log(isv('ab')(i));
```

output:

``` bash
3.511326342653452e+30
C:\Users\Luciano.Mammino\test\node_modules\indexed-string-variation\lib\index.js:38
      throw new TypeError('index must be a non-negative integer');
      ^

TypeError: index must be a non-negative integer
    at C:\Users\Luciano.Mammino\test\node_modules\indexed-string-variation\lib\index.js:38:13
    at Object.<anonymous> (C:\Users\Luciano.Mammino\test\test.js:5:22)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
```

**Comment by lmammino** [comment]
[this](http://silentmatt.com/biginteger-docs/files/biginteger-js.html) or [this](https://github.com/rauschma/strint) might be used to solve the issue
